#!/data/data/com.termux/files/usr/bin/bash
#
# TAKE THE STAGED BUILD, THEN START THE SERVER.
#
# The game runs this instead of run.sh, through Termux's RunCommandService.
#
# WHY IT EXISTS
#
# tools/stage_server.sh pushes a new Cosmic.jar and scripts.tar to
# /sdcard/Download/cosmic and reports every file as "ok", because they really
# do arrive. But nothing ever installed them: termux_setup.sh copies them into
# ~/cosmic only `if [ ! -f ]`, which is true exactly once, on the very first
# setup. So every build after the first landed on the device and was never
# run - for days - while the staging, the restart and the log all looked fine.
#
# The obvious fix is "run termux_setup.sh again", but that does `pkg update`
# and `pkg install` unconditionally: minutes of downloading, and it needs a
# network, to copy two files. This does only the copying, so it is cheap
# enough to run every single time the server starts.
#
# That matters more than it sounds. It means "restart the server" and "take
# the new build" stop being two different jobs, one of which somebody has to
# remember. There is now no way to be running a stale server by accident.
#
set -u

STAGE=/sdcard/Download/cosmic

# EVERYTHING FROM HERE GOES SOMEWHERE READABLE FROM A PC.
#
# Termux's RunCommandService throws stdout away, and run.sh's own log lives in
# Termux's home, which adb cannot see. So when the server failed to start
# there was no output anywhere on either machine - the game cheerfully logged
# "starting the server" and nothing else ever happened.
#
# /sdcard/Download/cosmic is the one directory both sides can reach:
#
#     adb shell cat /sdcard/Download/cosmic/bootstrap.log
exec >> "$STAGE/bootstrap.log" 2>&1

echo
echo "=================================================="
echo "bootstrap at $(date)"

cd "$HOME/cosmic" 2>/dev/null || {
	echo "FAILED: no $HOME/cosmic - termux_setup.sh has never been run"
	exit 1
}

echo "  in $PWD"

UPDATED=0

# DIFFERENT, NOT NEWER. Compared by CONTENT, never by timestamp.
#
# This used to be `[ "$STAGE/Cosmic.jar" -nt Cosmic.jar ]`, and that is wrong
# in a way that hides itself perfectly.
#
# A staged jar carries the time it was BUILT. The installed copy carries the
# time it was COPIED - which is always later. So the moment a build is staged
# some minutes after the previous one was installed, the newer build looks
# OLDER than the older install and is silently skipped. The log then prints
# the installed jar's date and the whole thing reads as fine.
#
# That is exactly what happened: a jar built at 04:04 was staged over one
# installed at 04:27, bootstrap said nothing at all, and the server went on
# running code from two builds back while the log gave no hint of it.
#
# `cmp -s` asks the only question that matters - is the file on the device the
# same file? - and no clock can fool it. It also makes deliberately staging an
# OLDER build work, to back something out, which the timestamp test refused.
if [ -d "$STAGE" ]; then
	if [ -f "$STAGE/Cosmic.jar" ] && ! cmp -s "$STAGE/Cosmic.jar" Cosmic.jar; then
		echo "  installing a different Cosmic.jar"
		cp "$STAGE/Cosmic.jar" Cosmic.jar && UPDATED=1 \
			|| echo "  FAILED to copy the jar"
	fi

	# The tar is compared against A COPY OF THE TAR, not against the folder it
	# was unpacked into. Comparing a file with a directory was the same mistake
	# wearing a different hat: `scripts` gets touched by anything that writes a
	# script, and from then on the tar looks stale for ever.
	if [ -f "$STAGE/scripts.tar" ] && ! cmp -s "$STAGE/scripts.tar" .scripts.installed; then
		echo "  unpacking new scripts"

		# Over the top rather than a wipe: a script somebody wrote by hand on
		# the device is worth more than tidiness.
		if tar -xf "$STAGE/scripts.tar"; then
			cp "$STAGE/scripts.tar" .scripts.installed
			UPDATED=1
		else
			echo "  FAILED to unpack the scripts"
		fi
	fi

	# run.sh is regenerated by termux_setup.sh and may have gained fixes.
	if [ -f "$STAGE/run.sh" ] && ! cmp -s "$STAGE/run.sh" run.sh; then
		echo "  taking a different run.sh"
		cp "$STAGE/run.sh" run.sh && chmod +x run.sh
	fi

	# THE CONFIG, which was staged and then never installed.
	#
	# stage_server.sh has always sent config.yaml and this script has never
	# looked at it, so every server setting was frozen at whatever the
	# one-off Termux setup wrote. Changing a rule on the PC, sending it, and
	# restarting the server did EXACTLY NOTHING, and said so nowhere - the
	# staged file was sitting right there next to the jar being installed.
	#
	# Same content test as everything else here: a config edited on the
	# device by hand is not clobbered by an identical one.
	if [ -f "$STAGE/config.yaml" ] && ! cmp -s "$STAGE/config.yaml" config.yaml; then
		echo "  installing a different config.yaml"
		cp "$STAGE/config.yaml" config.yaml && UPDATED=1 \
			|| echo "  FAILED to copy the config"
	fi
else
	echo "  nothing staged at $STAGE"
fi

# A NEW BUILD MEANS THE RUNNING ONE IS STALE.
#
# run.sh refuses to start a second server when the login port is taken, which
# is right - seven of them were once found on this device. But it makes
# RESTARTING impossible: HOST could only ever start a server, never replace
# one. So a jar copied in at 05:36 sat on disk while a process from 02:26 went
# on serving, and every symptom looked like the code not working rather than
# the code not running. Three hours of it.
#
# If something was actually replaced just now, the thing running is by
# definition out of date and has to go. Nothing is killed when nothing
# changed, so an ordinary HOST on an already-running server still does
# nothing, which is what that guard was for.
if [ "$UPDATED" = "1" ]; then
	if pgrep -f '[C]osmic\.jar' >/dev/null 2>&1; then
		echo "  a newer build was installed - stopping the old server"

		pkill -f '[C]osmic\.jar'

		# Wait for the login port to come free rather than guessing. A JVM
		# with a database behind it does not close its sockets instantly, and
		# starting into a port that is still held is how the seven happened.
		for i in $(seq 1 30); do
			netstat -ltn 2>/dev/null | grep -q ':8484 ' || break
			sleep 1
		done

		if netstat -ltn 2>/dev/null | grep -q ':8484 '; then
			echo "  it did not let go of the port - forcing"
			pkill -9 -f '[C]osmic\.jar'
			sleep 2
		fi

		# AND WAIT FOR THE PROCESS TO GO, not just the port.
		#
		# run.sh has TWO guards: the login port, and a pgrep for the jar. The
		# port is the one its own comment argues for - "a Cosmic that is still
		# shutting down holds no port and should not block a restart" - and
		# then the very next block adds the pgrep test that does exactly that.
		#
		# So a JVM that had released 8484 but had not finished dying was
		# enough for run.sh to answer "the server is already running" and exit
		# 0. Which is what happened on the RP5: the old server was stopped,
		# the new one was never started, and the log said everything had gone
		# fine. The device sat there with no server at all.
		#
		# Waiting for both satisfies both guards, and leaves run.sh alone -
		# it is generated on the device by termux_setup.sh and is not staged,
		# so a fix there would not travel.
		for i in $(seq 1 20); do
			pgrep -f '[C]osmic\.jar' >/dev/null 2>&1 || break
			sleep 1
		done

		if pgrep -f '[C]osmic\.jar' >/dev/null 2>&1; then
			echo "  it is still there - forcing"
			pkill -9 -f '[C]osmic\.jar'
			sleep 2
		fi

		echo "  old server stopped"
	fi
fi

if [ ! -f run.sh ]; then
	echo "FAILED: no run.sh in $PWD"
	exit 1
fi

if [ ! -f Cosmic.jar ]; then
	echo "FAILED: no Cosmic.jar in $PWD"
	exit 1
fi

echo "  jar   $(stat -c %y Cosmic.jar 2>/dev/null)"
echo "  java  $(command -v java || echo MISSING)"
# THE SERVER LOG, MIRRORED OUT.
#
# Cosmic writes to ~/cosmic/cosmic.log and ~/cosmic/logs/cosmic-log.log, both
# inside Termux's private home, which adb cannot read and the game cannot
# reach. So for this whole project the server has been a black box: when it
# misbehaved there was nothing to look at from either machine, and every
# diagnosis had to be a guess.
#
# A copy every few seconds into the staging directory fixes that:
#
#     adb shell cat /sdcard/Download/cosmic/server.log
#
# Cheap, and it dies with the server because it watches for the parent.
(
	while sleep 5; do
		cp -f cosmic.log "$STAGE/server.log" 2>/dev/null
		cp -f logs/cosmic-log.log "$STAGE/server-warn.log" 2>/dev/null

		# Stop when nothing is running any more, or this outlives the server
		# and spins for ever.
		pgrep -f Cosmic.jar >/dev/null 2>&1 || exit 0
	done
) >/dev/null 2>&1 &

echo "  starting the server - further output goes to $PWD/cosmic.log"

exec bash ./run.sh
