"""Find where this client does less than the fork it is being filled in from.

Every bug worth a session lately has been the same shape: our file implements
a FRACTION of what the protocol or the data expects, and says nothing about
the rest. The NPC dialog parser handled 3 of ~15 markup codes. Reactor.cpp
carried `// TODO: hit/break sounds`. Neither needed a player to find - both
were visible in the source.

So look, instead of waiting to be told. For every file present in both trees
this reports how much bigger theirs is, and which functions exist there and
not here. Big gaps are where the next silent bug lives.

    python tools/divergence.py                 # ranked summary
    python tools/divergence.py Character/Char  # detail for one file

It compares text, not behaviour. A file can be larger for reasons that do not
matter to us, and a file we deliberately rewrote (anything touching Android,
GLES or the second screen) will look "behind" when it is simply different.
Read the ranking as a list of places to LOOK, never as a list of work.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
THEIRS = os.path.join(os.path.dirname(ROOT), 'OpenStory', 'src')

DIRS = ['Audio', 'Character', 'Data', 'Gameplay', 'Graphics', 'IO', 'Net',
        'Template', 'Util']

# Ours on purpose: the Android port, the second screen, and the tooling built
# around them. These are the reason this fork exists, so being "behind" their
# version is meaningless - there is nothing on their side to be behind.
OURS_BY_DESIGN = ('Android', 'SecondScreen', 'GraphicsGL', 'Window')

# A definition at file scope: `Type Class::method(args)`. Deliberately loose -
# the aim is a comparable set of names on both sides, not a parser.
# The leading whitespace matters: everything here lives inside `namespace ms`
# and so is indented. Anchoring at column 0 matched nothing at all, and the
# report cheerfully printed "0 functions missing" for every file in the tree.
DEFINITION = re.compile(
    r'^[ \t]*[A-Za-z_][\w:<>,\s\*&]*?\b([A-Za-z_]\w*)::([A-Za-z_~]\w*)\s*\(',
    re.M)


def read(path):
    try:
        with open(path, encoding='utf-8', errors='replace') as f:
            return f.read()
    except OSError:
        return None


def definitions(text):
    return {f'{cls}::{fn}' for cls, fn in DEFINITION.findall(text)} if text else set()


def significant(text):
    """Lines that are not blank and not comment-only, so a heavily commented
    file is not mistaken for a large one."""
    if not text:
        return 0
    n = 0
    for line in text.splitlines():
        s = line.strip()
        if s and not s.startswith(('//', '/*', '*', '#include')):
            n += 1
    return n


def pairs():
    for d in DIRS:
        for dirpath, _, names in os.walk(os.path.join(ROOT, d)):
            for name in names:
                if not name.endswith(('.cpp', '.h')):
                    continue
                ours = os.path.join(dirpath, name)
                rel = os.path.relpath(ours, ROOT).replace('\\', '/')
                yield rel, ours, os.path.join(THEIRS, rel)


def main():
    if not os.path.isdir(THEIRS):
        sys.exit(f'OpenStory not found at {THEIRS}')

    only_theirs = []
    rows = []

    for rel, ours_path, theirs_path in pairs():
        if not os.path.exists(theirs_path):
            continue

        ours = read(ours_path)
        theirs = read(theirs_path)

        o_lines, t_lines = significant(ours), significant(theirs)
        missing = definitions(theirs) - definitions(ours)

        rows.append((rel, o_lines, t_lines, missing))

    # Files they have that we do not exist too, and are the loudest signal of
    # all: a whole subsystem nobody has written here.
    for dirpath, _, names in os.walk(THEIRS):
        for name in names:
            if not name.endswith(('.cpp', '.h')):
                continue
            rel = os.path.relpath(os.path.join(dirpath, name),
                                  THEIRS).replace('\\', '/')
            if not os.path.exists(os.path.join(ROOT, rel)):
                only_theirs.append(rel)

    if len(sys.argv) > 1:
        want = sys.argv[1].replace('\\', '/')
        for rel, o, t, missing in rows:
            if want in rel:
                print(f'{rel}: {o} significant lines here, {t} there')
                for name in sorted(missing):
                    print(f'  missing: {name}')
        return

    print('# Where we do less than OpenStory')
    print()
    print('Generated by `tools/divergence.py`. Text, not behaviour: a file can')
    print('be larger for reasons that do not matter to us, and anything we')
    print('rewrote for Android or the second screen will look "behind" when it')
    print('is only different. A list of places to LOOK, not a list of work.')
    print()

    print(f'## Whole files only they have - {len(only_theirs)}')
    print()
    for rel in sorted(only_theirs):
        print(f'- `{rel}`')
    print()

    print('## Files where theirs is substantially bigger')
    print()
    print('Ranked by how many function definitions exist there and not here.')
    print()

    ranked = sorted(rows, key=lambda r: (-len(r[3]), r[1] - r[2]))

    for rel, o, t, missing in ranked:
        if not missing and t <= o * 1.25:
            continue

        flag = ' (ours by design)' if any(k in rel for k in OURS_BY_DESIGN) else ''
        ratio = f'{t / o:.1f}x' if o else 'new'

        print(f'### {rel}{flag}')
        print(f'{o} lines here, {t} there ({ratio}), '
              f'{len(missing)} functions missing')
        print()

        for name in sorted(missing)[:12]:
            print(f'- `{name}`')
        if len(missing) > 12:
            print(f'- ...and {len(missing) - 12} more')
        print()


if __name__ == '__main__':
    main()
