"""Work out what the server can say that the client does not listen to.

Diffs Cosmic's SendOpcode.java against the handlers actually registered in
Net/PacketSwitch.cpp, and - because this client is being filled in from a fork
that already did much of it - marks which of the gaps OpenStory has already
implemented, so a gap can be told apart from a job.

    python tools/packet_gap.py > docs_PACKET_GAP.md

Paths are relative to the repository root and assume Cosmic and OpenStory are
checked out beside it.

A caveat that matters more than the numbers: THIS ONLY FINDS ONE KIND OF HOLE.
A packet nobody reads is easy to count. A packet that IS read, wrongly and
silently, does not appear here at all - and those have been the majority of
the real bugs. Treat a small "not handled" number as necessary, never
sufficient.
"""
import os
import re
import sys
from collections import OrderedDict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SIBLINGS = os.path.dirname(ROOT)

COSMIC = os.path.join(SIBLINGS, 'Cosmic', 'src', 'main', 'java', 'net',
                      'opcodes', 'SendOpcode.java')
OURS = os.path.join(ROOT, 'Net', 'PacketSwitch.cpp')
THEIRS = os.path.join(SIBLINGS, 'OpenStory', 'src', 'Net', 'PacketSwitch.cpp')

# Which subsystem a message belongs to, by substring of its name. First match
# wins, so order matters: the specific before the general.
GROUPS = OrderedDict([
    ('Pets', ('PET',)),
    ('Summons & doors', ('SUMMON', 'SPAWN_DOOR', 'DOOR', 'MIST')),
    ('Quests', ('QUEST',)),
    ('Guilds & alliances', ('GUILD', 'ALLIANCE', 'BBS')),
    ('Buddies & messaging', ('BUDDY', 'MESSENGER', 'WHISPER', 'CHAT')),
    ('Marriage & family', ('MARRIAGE', 'WEDDING', 'FAMILY', 'ENGAGE')),
    ('Cash shop', ('CS_', 'CASH', 'MTS')),
    ('Trading & shops', ('TRADE', 'PLAYER_INTERACTION', 'SHOP', 'STORAGE')),
    ('Parties & expeditions', ('PARTY', 'EXPEDITION')),
    ('Monster book & rings', ('MONSTER_BOOK', 'RING', 'CHARM')),
    ('Mini-games & events', ('MINI', 'EVENT', 'GACHAPON', 'RPS')),
    ('Map & field effects', ('FIELD', 'MAP', 'CLOCK', 'WEATHER', 'BOAT')),
    ('Combat & mobs', ('MOB', 'ATTACK', 'DAMAGE', 'SKILL', 'BUFF')),
])


def read(path, what):
    if not os.path.exists(path):
        sys.exit(f'cannot find {what}: {path}')
    with open(path, encoding='utf-8', errors='replace') as f:
        return f.read()


def server_messages():
    """{name: opcode} for everything the server can send."""
    text = read(COSMIC, "Cosmic's SendOpcode.java")
    out = OrderedDict()
    for name, value in re.findall(r'^\s*([A-Z][A-Z_0-9]*)\s*\(\s*(0x[0-9a-fA-F]+|\d+)\s*\)',
                                  text, re.M):
        out[name] = int(value, 0)
    return out


def handled_opcodes(path, what):
    """The set of opcode NUMBERS a client registers a handler for.

    Names differ between the two clients, so numbers are the only common
    ground. The enum gives name -> number; the emplace list says which of
    those names actually got a handler."""
    text = read(path, what)
    enum = {name: int(value, 0) for name, value in
            re.findall(r'^\s*([A-Z][A-Z_0-9]*)\s*=\s*(0x[0-9a-fA-F]+|\d+)\s*,',
                       text, re.M)}
    registered = re.findall(r'emplace<\s*([A-Z][A-Z_0-9]*)\s*,', text)
    return {enum[name] for name in registered if name in enum}


def group_of(name):
    for group, keys in GROUPS.items():
        if any(key in name for key in keys):
            return group
    return 'Everything else'


def main():
    messages = server_messages()
    ours = handled_opcodes(OURS, 'our PacketSwitch.cpp')
    theirs = handled_opcodes(THEIRS, "OpenStory's PacketSwitch.cpp")

    missing = [(n, op) for n, op in messages.items() if op not in ours]
    portable = [(n, op) for n, op in missing if op in theirs]

    print('# What the server says that the client does not hear')
    print()
    print('Generated by `tools/packet_gap.py`. Regenerate it after adding '
          'handlers.')
    print()
    print(f'- Messages the server can send: **{len(messages)}**')
    print(f'- Handled by the client: **{len(messages) - len(missing)}**')
    print(f'- Not handled: **{len(missing)}**')
    print(f'- Of those, already written in OpenStory: **{len(portable)}** '
          '(a port, not a rewrite)')
    print()
    print('**This only finds one kind of hole.** A packet nobody reads is easy')
    print('to count. A packet that is read *wrongly*, and silently, does not')
    print('appear here at all - and those have been most of the real bugs. The')
    print('client also prints `Unhandled packet detected, Opcode: N` while you')
    print('play, and anything seen there outranks anything guessed at here.')
    print()

    by_group = OrderedDict()
    for name, op in missing:
        by_group.setdefault(group_of(name), []).append((name, op))

    for group in list(GROUPS) + ['Everything else']:
        rows = by_group.get(group)
        if not rows:
            continue
        done = sum(1 for _, op in rows if op in theirs)
        print(f'## {group} - {len(rows)} missing, {done} already in OpenStory')
        print()
        for name, op in sorted(rows, key=lambda r: r[1]):
            mark = 'port' if op in theirs else 'from scratch'
            print(f'- `{name}` ({op}) - {mark}')
        print()


if __name__ == '__main__':
    main()
