"""Find bugs OpenStory fixed that we probably still have.

`divergence.py` answers "where do they do MORE than us", by counting. It
cannot answer "where do they do it BETTER", and that has been the more
expensive class: the Amherst reactors were four bugs in a file where OUR
version was the larger one.

But the fixes are not invisible. When OpenStory corrected something they
tended to write down what had been wrong - "silently rejects those", "the old
code only checked", "previously fell to NONE". So instead of diffing
behaviour, read their confessions.

This pulls comment blocks whose wording describes a fix, from files that
exist on both sides, and skips ones whose explanation already appears in our
copy - which is how a fix we have already taken drops off the list.

    python tools/theirfixes.py            # everything, grouped by file
    python tools/theirfixes.py Character  # one subtree

Each hit is a place to READ, not a defect. The comment may describe a bug we
never had, or code we deliberately wrote differently.
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
THEIRS = os.path.join(os.path.dirname(ROOT), 'OpenStory', 'src')

# Wording that suggests a comment is explaining a former defect rather than
# describing what the code does.
SMELLS = re.compile(
    r'\b(used to|previously|the old code|old behaviour|old behavior|silently|'
    r'would crash|crashed|was wrong|is wrong|incorrectly|instead of|'
    r'rather than|the bug|a bug|broken|never worked|did not work|'
    r'does not work|fails|failed|drops?|dropped|ignored|off by|'
    r'out of range|overflow|underflow|leak)\b', re.I)

# Wording common in ordinary descriptive comments that would otherwise trip
# the filter constantly.
BORING = re.compile(r'\b(instead of a|rather than a|drops? (the|an?) (item|meso))\b', re.I)


def comment_blocks(text):
    """Consecutive // lines, as one block, with the line number it starts at."""
    lines = text.splitlines()
    block, start = [], 0

    for i, line in enumerate(lines, 1):
        stripped = line.strip()

        if stripped.startswith('//'):
            if not block:
                start = i
            block.append(stripped.lstrip('/').strip())
        elif block:
            yield start, ' '.join(block)
            block = []

    if block:
        yield start, ' '.join(block)


def read(path):
    try:
        with open(path, encoding='utf-8', errors='replace') as f:
            return f.read()
    except OSError:
        return ''


def main():
    want = sys.argv[1].replace('\\', '/') if len(sys.argv) > 1 else ''
    hits = {}

    for dirpath, _, names in os.walk(THEIRS):
        for name in names:
            if not name.endswith(('.cpp', '.h')):
                continue

            their_path = os.path.join(dirpath, name)
            rel = os.path.relpath(their_path, THEIRS).replace('\\', '/')

            if want and want not in rel:
                continue

            our_path = os.path.join(ROOT, rel)

            # A file we do not have is divergence.py's job, not this one.
            if not os.path.exists(our_path):
                continue

            ours = read(our_path)

            for line_no, text in comment_blocks(read(their_path)):
                if len(text) < 40 or not SMELLS.search(text) or BORING.search(text):
                    continue

                # If a distinctive chunk of their explanation is already in our
                # file, we have taken this fix.
                probe = text[:60]
                if probe and probe in ours:
                    continue

                hits.setdefault(rel, []).append((line_no, text))

    if not hits:
        print('nothing found')
        return

    print('# Fixes OpenStory documented, in files we share')
    print()
    print('Generated by `tools/theirfixes.py`. Their comments explaining what')
    print('used to be wrong, from files that exist on both sides, minus the')
    print('ones whose wording already appears in our copy.')
    print()
    print('A place to READ, not a defect. The comment may describe a bug we')
    print('never had, or code we wrote differently on purpose.')
    print()

    for rel in sorted(hits, key=lambda r: -len(hits[r])):
        print(f'## {rel} - {len(hits[rel])}')
        print()
        for line_no, text in hits[rel]:
            if len(text) > 300:
                text = text[:300] + '...'
            print(f'- **:{line_no}** {text}')
        print()


if __name__ == '__main__':
    main()
